version: '3'
services:
  app:
    image: eduardomota/nginx_php-fpm:8
    container_name: nginx_php-fpm8
    restart: always
    ports:
      - 80:80
    volumes:
      - ./public_html:/var/www/html
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
