version: '3'
services:
  app:
    image: eduardomota/owa
    container_name: open-web-analytics
    volumes:
      - ./public_html:/var/www/html
    depends_on:
      - database
    networks:
      - default
    ports:
      - 80:80
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
  database:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
